/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanPopup: typeof import('vant/es')['Popup']
  }
}

// For TSX support
declare global {
  const VanButton: typeof import('vant/es')['Button']
  const VanCheckbox: typeof import('vant/es')['Checkbox']
  const VanField: typeof import('vant/es')['Field']
  const VanForm: typeof import('vant/es')['Form']
  const VanPopup: typeof import('vant/es')['Popup']
}